CC      = gcc
CFLAGS  = -O2 -std=c18
LDFLAGS = -lpdcurses
TARGET  = jankman.exe
OBJS    = jankman.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) *^ $(LDFLAGS)

clean:
	del /F $(TARGET) $(OBJS)

rebuild: clean all
